// Defining UI Actions
export const SHOW_SPINNER = "SHOW_SPINNER";
export const HIDE_SPINNER = "HIDE_SPINNER";

// Defining VoicemailBox Actions
export const FETCH_VOICEMAILBOXES = "FETCH_VOICEMAILBOXES";
export const FETCHED_VOICEMAILBOXES = "FETCHED_VOICEMAILBOXES";
export const FETCHING_VOICEMAILBOXES = "FETCHING_VOICEMAILBOXES";
export const FETCH_VOICEMAILBOXES_SUCCESS = "FETCH_VOICEMAILBOXES_SUCCESS";
export const FETCHING_VOICEMAILBOX = "FETCHING_VOICEMAILBOX";
export const FETCHED_VOICEMAILBOX = "FETCHED_VOICEMAILBOX";

// Defining VoicemailBox Actions
export const FETCHING_VOICEMAILMESSAGES = "FETCHING_VOICEMAILMESSAGES";
export const FETCHED_VOICEMAILMESSAGES = "FETCHED_VOICEMAILMESSAGES";
